[2022-11-15 16:52:46,112] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-13T00:00:00+00:00 [queued]>
[2022-11-15 16:52:46,176] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-13T00:00:00+00:00 [queued]>
[2022-11-15 16:52:46,179] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-11-15 16:52:46,180] {taskinstance.py:1377} INFO - Starting attempt 3 of 6
[2022-11-15 16:52:46,181] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-11-15 16:52:46,262] {taskinstance.py:1397} INFO - Executing <Task(S3KeySensor): S3BucketSensorNewFiles> on 2022-11-13 00:00:00+00:00
[2022-11-15 16:52:46,280] {standard_task_runner.py:52} INFO - Started process 1585 to run task
[2022-11-15 16:52:46,293] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'DAG_Minio_S3_Wait_for_File', 'S3BucketSensorNewFiles', 'scheduled__2022-11-13T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/sensor.py', '--cfg-path', '/tmp/tmp_aqaqjgo', '--error-file', '/tmp/tmpo5mwzzdh']
[2022-11-15 16:52:46,297] {standard_task_runner.py:80} INFO - Job 20: Subtask S3BucketSensorNewFiles
[2022-11-15 16:52:46,553] {task_command.py:371} INFO - Running <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-13T00:00:00+00:00 [running]> on host 73a41ac08797
[2022-11-15 16:52:47,074] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Maico Bernal
AIRFLOW_CTX_DAG_ID=DAG_Minio_S3_Wait_for_File
AIRFLOW_CTX_TASK_ID=S3BucketSensorNewFiles
AIRFLOW_CTX_EXECUTION_DATE=2022-11-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-13T00:00:00+00:00
[2022-11-15 16:52:47,084] {s3.py:104} INFO - Poking for key : s3://data/precio*
[2022-11-15 16:52:47,115] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2022-11-15 16:52:47,122] {base_aws.py:210} INFO - Credentials retrieved from extra_config
[2022-11-15 16:52:47,999] {base.py:301} INFO - Success criteria met. Exiting.
[2022-11-15 16:52:48,149] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=DAG_Minio_S3_Wait_for_File, task_id=S3BucketSensorNewFiles, execution_date=20221113T000000, start_date=20221115T165246, end_date=20221115T165248
[2022-11-15 16:52:48,294] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-15 16:52:48,546] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
