[2022-11-15 16:53:14,510] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-12T00:00:00+00:00 [queued]>
[2022-11-15 16:53:14,543] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-12T00:00:00+00:00 [queued]>
[2022-11-15 16:53:14,545] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-11-15 16:53:14,546] {taskinstance.py:1377} INFO - Starting attempt 3 of 6
[2022-11-15 16:53:14,547] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-11-15 16:53:14,625] {taskinstance.py:1397} INFO - Executing <Task(S3KeySensor): S3BucketSensorNewFiles> on 2022-11-12 00:00:00+00:00
[2022-11-15 16:53:14,636] {standard_task_runner.py:52} INFO - Started process 1616 to run task
[2022-11-15 16:53:14,644] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'DAG_Minio_S3_Wait_for_File', 'S3BucketSensorNewFiles', 'scheduled__2022-11-12T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/sensor.py', '--cfg-path', '/tmp/tmp4aqn91_q', '--error-file', '/tmp/tmpocu6qd2e']
[2022-11-15 16:53:14,647] {standard_task_runner.py:80} INFO - Job 23: Subtask S3BucketSensorNewFiles
[2022-11-15 16:53:14,808] {task_command.py:371} INFO - Running <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-12T00:00:00+00:00 [running]> on host 73a41ac08797
[2022-11-15 16:53:15,103] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Maico Bernal
AIRFLOW_CTX_DAG_ID=DAG_Minio_S3_Wait_for_File
AIRFLOW_CTX_TASK_ID=S3BucketSensorNewFiles
AIRFLOW_CTX_EXECUTION_DATE=2022-11-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-12T00:00:00+00:00
[2022-11-15 16:53:15,107] {s3.py:104} INFO - Poking for key : s3://data/precio*
[2022-11-15 16:53:15,129] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2022-11-15 16:53:15,134] {base_aws.py:210} INFO - Credentials retrieved from extra_config
[2022-11-15 16:53:15,686] {base.py:301} INFO - Success criteria met. Exiting.
[2022-11-15 16:53:15,755] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=DAG_Minio_S3_Wait_for_File, task_id=S3BucketSensorNewFiles, execution_date=20221112T000000, start_date=20221115T165314, end_date=20221115T165315
[2022-11-15 16:53:15,823] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-15 16:53:16,006] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
