[2022-11-15 16:53:14,449] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2022-11-15 16:53:14,492] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2022-11-15 16:53:14,493] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-11-15 16:53:14,494] {taskinstance.py:1377} INFO - Starting attempt 3 of 6
[2022-11-15 16:53:14,495] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-11-15 16:53:14,555] {taskinstance.py:1397} INFO - Executing <Task(S3KeySensor): S3BucketSensorNewFiles> on 2022-11-14 00:00:00+00:00
[2022-11-15 16:53:14,576] {standard_task_runner.py:52} INFO - Started process 1614 to run task
[2022-11-15 16:53:14,587] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'DAG_Minio_S3_Wait_for_File', 'S3BucketSensorNewFiles', 'scheduled__2022-11-14T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/sensor.py', '--cfg-path', '/tmp/tmpwd3mgpfc', '--error-file', '/tmp/tmpmrcethgf']
[2022-11-15 16:53:14,591] {standard_task_runner.py:80} INFO - Job 22: Subtask S3BucketSensorNewFiles
[2022-11-15 16:53:14,758] {task_command.py:371} INFO - Running <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-14T00:00:00+00:00 [running]> on host 73a41ac08797
[2022-11-15 16:53:15,033] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Maico Bernal
AIRFLOW_CTX_DAG_ID=DAG_Minio_S3_Wait_for_File
AIRFLOW_CTX_TASK_ID=S3BucketSensorNewFiles
AIRFLOW_CTX_EXECUTION_DATE=2022-11-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-14T00:00:00+00:00
[2022-11-15 16:53:15,039] {s3.py:104} INFO - Poking for key : s3://data/precio*
[2022-11-15 16:53:15,074] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2022-11-15 16:53:15,079] {base_aws.py:210} INFO - Credentials retrieved from extra_config
[2022-11-15 16:53:15,685] {base.py:301} INFO - Success criteria met. Exiting.
[2022-11-15 16:53:15,755] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=DAG_Minio_S3_Wait_for_File, task_id=S3BucketSensorNewFiles, execution_date=20221114T000000, start_date=20221115T165314, end_date=20221115T165315
[2022-11-15 16:53:15,818] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-15 16:53:16,006] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
