[2022-11-15 16:40:52,173] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles manual__2022-11-15T16:40:46.257885+00:00 [queued]>
[2022-11-15 16:40:52,269] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles manual__2022-11-15T16:40:46.257885+00:00 [queued]>
[2022-11-15 16:40:52,274] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-11-15 16:40:52,282] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2022-11-15 16:40:52,285] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-11-15 16:40:52,445] {taskinstance.py:1397} INFO - Executing <Task(S3KeySensor): S3BucketSensorNewFiles> on 2022-11-15 16:40:46.257885+00:00
[2022-11-15 16:40:52,480] {standard_task_runner.py:52} INFO - Started process 857 to run task
[2022-11-15 16:40:52,525] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'DAG_Minio_S3_Wait_for_File', 'S3BucketSensorNewFiles', 'manual__2022-11-15T16:40:46.257885+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/sensor.py', '--cfg-path', '/tmp/tmpxpezy28p', '--error-file', '/tmp/tmp2kmtnyuq']
[2022-11-15 16:40:52,532] {standard_task_runner.py:80} INFO - Job 11: Subtask S3BucketSensorNewFiles
[2022-11-15 16:40:52,784] {task_command.py:371} INFO - Running <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles manual__2022-11-15T16:40:46.257885+00:00 [running]> on host 73a41ac08797
[2022-11-15 16:40:53,987] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Maico Bernal
AIRFLOW_CTX_DAG_ID=DAG_Minio_S3_Wait_for_File
AIRFLOW_CTX_TASK_ID=S3BucketSensorNewFiles
AIRFLOW_CTX_EXECUTION_DATE=2022-11-15T16:40:46.257885+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-15T16:40:46.257885+00:00
[2022-11-15 16:40:54,153] {s3.py:104} INFO - Poking for key : s3://data/precio*
[2022-11-15 16:40:54,290] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2022-11-15 16:40:54,308] {base_aws.py:210} INFO - Credentials retrieved from extra_config
[2022-11-15 16:40:58,981] {base.py:301} INFO - Success criteria met. Exiting.
[2022-11-15 16:40:59,502] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=DAG_Minio_S3_Wait_for_File, task_id=S3BucketSensorNewFiles, execution_date=20221115T164046, start_date=20221115T164052, end_date=20221115T164059
[2022-11-15 16:40:59,665] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-15 16:40:59,928] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
